const correcciones = [
    // -- Casos que reordenan o son muy específicos (PRIMERO) --
    [/figueroa alcorta jose pres av/g, 'avenida figueroa alcorta'],
    [/berro adolfo av/g, 'avenida adolfo berro'],
    [/berro adolfo/g, 'avenida adolfo berro'],
    [/lacroze federico av/g, 'avenida federico lacroze'],
    [/diaz cnel av/g, 'avenida coronel diaz'],
    [/justo juan b av/g, 'avenida juan b. justo'],
    [/campos luis maria av/g, 'avenida luis maria campos'],
    [/lugones leopoldo av/g, 'avenida leopoldo lugones'],
    [/scalabrini ortiz av/g, 'avenida raul scalabrini ortiz'],
    [/cabrera jose antonio/g, 'jose antonio cabrera'],
    [/bullrich int av/g, 'avenida intendente bullrich'],
    [/int bullrich/g, 'avenida intendente bullrich'],
    [/vega n cnel/g, 'coronel niceto vega'],
    [/cnel m freyre/g, 'avenida coronel marcelino e. freyre'],
    [/gral l n mansilla/g, 'gral. lucio norberto mansilla'],
    [/gral savio manuel n/g, 'gral. manuel n. savio'],
    [/manuel n savio/g, 'gral. manuel n. savio'],
    [/infanta isabel av/g, 'avenida infanta isabel'],
    [/pedro montt av/g, 'avenida presidente pedro montt'],
    [/las heras gral av/g, 'avenida gral. las heras'],
    [/obligado r av costanera/g, 'avenida costanera'],
    [/obligado rafael av c/g, 'avenida costanera'],
    [/castilla ramon mcal/g, 'mariscal ramon castilla'],
    [/newbery jorge av/g, 'avenida jorge newbery'],

    // -- Correcciones de Avenidas --
    [/av del libertador/g, 'avenida del libertador'],
    [/av libertador/g, 'avenida del libertador'],
    [/del libertador/g, 'avenida del libertador'],
    [/libertador/g, 'avenida del libertador'],
    [/av f lacroze/g, 'avenida federico lacroze'],
    [/fco lacroze/g, 'avenida federico lacroze'],
    [/f lacroze/g, 'avenida federico lacroze'],
    [/av cnel diaz/g, 'avenida coronel diaz'],
    [/coronel diaz/g, 'avenida coronel diaz'],
    [/cnel diaz/g, 'avenida coronel diaz'],
    [/c diaz/g, 'avenida coronel diaz'],
    [/av figueroa alcorta/g, 'avenida figueroa alcorta'],
    [/figueroa alcorta/g, 'avenida figueroa alcorta'],
    [/av juan b justo/g, 'avenida juan b. justo'],
    [/juan b justo/g, 'avenida juan b. justo'],
    [/av luis maria campos/g, 'avenida luis maria campos'],
    [/luis maria campos/g, 'avenida luis maria campos'],
    [/luis m campos/g, 'avenida luis maria campos'],
    [/l m campos/g, 'avenida luis maria campos'],
    [/av r scalabrini ortiz/g, 'avenida raul scalabrini ortiz'],
    [/av raul s ortiz/g, 'avenida raul scalabrini ortiz'],
    [/scalabrini ortiz/g, 'avenida raul scalabrini ortiz'],
    [/av i chenaut/g, 'avenida general indalecio chenaut'],
    [/gral i chenaut/g, 'avenida general indalecio chenaut'],
    [/chenaut/g, 'avenida general indalecio chenaut'],
    [/av j newbery/g, 'avenida jorge newbery'],
    [/jorge newbery/g, 'avenida jorge newbery'],
    [/j newbery/g, 'avenida jorge newbery'],
    [/av b roldan/g, 'avenida belisario roldan'],
    [/av adolfo berro/g, 'avenida adolfo berro'],
    [/sarmiento/g, 'avenida sarmiento'],
    [/casares/g, 'avenida casares'],
    [/cervio/g, 'avenida cerviño'],
    [/colombia/g, 'avenida colombia'],
    [/cordoba/g, 'avenida cordoba'],
    [/de los ombues/g, 'avenida de los ombues'],
    [/e tornquist/g, 'avenida ernesto tornquist'],
    [/infanta isabel/g, 'avenida infanta isabel'],
    [/iraola/g, 'avenida iraola'],
    [/medrano/g, 'avenida medrano'],
    [/cabildo/g, 'avenida cabildo'],
    [/dorrego/g, 'avenida dorrego'],
    [/santa fe/g, 'avenida santa fe'],
    [/las heras/g, 'avenida gral. las heras'],

    // -- Correcciones de Calles y Pasajes --
    [/acua de figueroa/g, 'francisco acuña de figueroa'],
    [/a j carranza/g, 'angel justiniano carranza'],
    [/angel j. carranza/g, 'angel justiniano carranza'],
    [/angel carranza/g, 'angel justiniano carranza'],
    [/m de aguado/g, 'c. alejandro m. de aguado'],
    [/cnel niceto vega/g, 'coronel niceto vega'],
    [/niceto vega/g, 'coronel niceto vega'],
    [/benjamin matienzo/g, 'teniente benjamin matienzo'],
    [/jose a cabrera/g, 'jose antonio cabrera'],
    [/cabrera/g, 'jose antonio cabrera'],
    [/fray j santa maria de oro/g, 'fray justo sta. maria de oro'],
    [/fray santa maria de oro/g, 'fray justo sta. maria de oro'],
    [/f j sta m de oro/g, 'fray justo sta. maria de oro'],
    [/f j s m de oro/g, 'fray justo sta. maria de oro'],
    [/juan f segui/g, 'juan francisco segui'],
    [/j f segui/g, 'juan francisco segui'],
    [/f segui/g, 'juan francisco segui'],
    [/mansilla/g, 'gral. lucio norberto mansilla'],
    [/dr emilio ravignani/g, 'dr. emilio ravignani'],
    [/e ravignani/g, 'dr. emilio ravignani'],
    [/j alvarez/g, 'julian alvarez'],
    [/john f kennedy/g, 'john fitzgerald kennedy'],
    [/j f kennedy/g, 'john fitzgerald kennedy'],
    [/j hernandez/g, 'jose hernandez'],
    [/j l borges/g, 'jorge luis borges'],
    [/j m gutierrez/g, 'juan maria gutierrez'],
    [/j mora fernandez/g, 'juan mora fernandez'],
    [/j salguero/g, 'jeronimo salguero'],
    [/jose l pagano/g, 'jose leon pagano'],
    [/juan a buschiazzo/g, 'pasaje juan a. buschiazzo'],
    [/m c marchi/g, 'maria catalina marchi'],
    [/m t de alvear/g, 'marcelo torcuato de alvear'],
    [/monseor v f zazpe/g, 'c. monseñor vicente zazpe'],
    [/anasagasti/g, 'pasaje anasagasti'],
    [/e zola/g, 'pasaje emilio zola'],
    [/el lazo/g, 'pasaje el lazo'],
    [/mason/g, 'pasaje mason'],
    [/cramer/g, 'costa rica'],
    [/guemes/g, 'güemes'],
    [/arribeos/g, 'arribeños'],
    [/bompland/g, 'bonpland'],
    [/carrasco/g, 'acceso punta carrasco'],
    [/palestina/g, 'estado de palestina'],
    [/independencia/g, 'soldado de la independencia'],
    // Agrega estas reglas AL PRINCIPIO de tu array 'correcciones'

    // -- REGLAS NUEVAS (Basadas en tu muestra) --

    // Abreviaturas de "Republica"
    [/^rep arabe siria/g, 'republica arabe siria'],
    [/^rep de eslovenia/g, 'republica de eslovenia'],
    [/^rep de la india/g, 'republica de la india'],
    [/^rep dominicana/g, 'republica dominicana'],

    // Abreviaturas de Nombres (S. L. Ruggieri, S. de Bustamante, etc.)
    [/^s l ruggieri/g, 'silvio l. ruggieri'],
    [/^s de bustamante/g, 'sanchez de bustamante'],
    [/^s dumont/g, 'santos dumont'],
    [/^santos dumont/g, 'santos dumont'], // Para unificar las que tienen junk
    [/^s martin d tours/g, 'san martin de tours'],
    [/^t garcia/g, 'teodoro garcia'],
    [/^tte b matienzo/g, 'teniente benjamin matienzo'],
    [/^tte gral e frias/g, 'teniente general e. frias'],
    [/^tte gral peron/g, 'teniente general peron'],
    [/^thames gree/g, 'thames'], // Corregir typo

    // Nombres invertidos
    [/^scalabrini ortiz raul av/g, 'avenida raul scalabrini ortiz'],
    [/^tornquist ernesto av/g, 'avenida ernesto tornquist'],
    [/^zazpe vicente f monseor/g, 'monseñor vicente f. zazpe'],

    // Casos de "San" y "Soldado"
    [/^san benito d palermo/g, 'san benito de palermo'],
    [/^san b de palermo/g, 'san benito de palermo'],
    [/^s b de palermo/g, 'san benito de palermo'],
    [/^s d l independencia/g, 'soldado de la independencia'],
    [/^s de la independencia/g, 'soldado de la independencia'],

    // Correcciones generales
    [/pje/g, 'pasaje'],
    [/vuelta d obligado/g, 'vuelta de obligado'],

    // -- FIN DE REGLAS NUEVAS --
];

module.exports = correcciones;
